export { useCreateProductMutation as useCreateProduct } from '@/apis/mutations/product_mutations'
export { useDeleteProductMutation as useDeleteProduct } from '@/apis/mutations/product_mutations'
export { useUpdateProductMutation as useUpdateProduct } from '@/apis/mutations/product_mutations'
export { useCreateSaleMutation as useCreateSale } from '@/apis/mutations/sale_mutations'
export { useDashboardStatsQuery as useDashboardStats } from '@/apis/queries/dashboard_queries'
export { useProductsQuery as useProducts } from '@/apis/queries/product_queries'
export { useSalesQuery as useSales } from '@/apis/queries/sale_queries'
